const exerciseImages = {
  sit: "assets/exercises/sit-to-stand.png",
  heel: "assets/exercises/heel-raise.png",
  seated: "assets/exercises/seated-march.png",
  wall: "assets/exercises/wall-slide.png",
  side: "assets/exercises/side-step.png",
  balance: "assets/exercises/tandem-stance.png",
  reach: "assets/exercises/reaching-cup.png",
  step: "assets/exercises/step-up.png",
  ankle: "assets/exercises/ankle-mobility.png",
  supineLeg: "assets/exercises/supine-leg-raise.png",
  bridge: "assets/exercises/bridge-exercise.png",
  hand: "assets/exercises/hand-therapy.png",
  button: "assets/exercises/button-practice.png",
  zipper: "assets/exercises/zipper-practice.png",
  spoon: "assets/exercises/spoon-practice.png",
  towel: "assets/exercises/towel-folding.png",
  bedRoll: "assets/exercises/bed-rolling.png",
  supineSit: "assets/exercises/supine-to-sit.png",
  breathing: "assets/exercises/breathing.png",
  neck: "assets/exercises/neck-exercise.png",
  band: "assets/exercises/band-row.png",
  reacher: "assets/exercises/reacher-tool.png",
  threshold: "assets/exercises/threshold-step.png",
  scanning: "assets/exercises/visual-scanning.png",
  ball: "assets/exercises/ball-toss.png",
  bilateralArm: "assets/exercises/bilateral-arm-lift.png",
  wallPush: "assets/exercises/wall-push-up.png",
  toiletTransfer: "assets/exercises/toilet-transfer.png"
};

const exerciseRows = [
  ["sit-to-stand", "坐到站訓練", "肌力訓練", "下肢|站姿|ADL", "由穩固椅子坐姿起身至站立，再慢慢坐回，訓練大腿肌力與轉位能力。", "雙腳與肩同寬、身體微向前傾，起身時膝蓋朝腳尖方向，避免快速跌坐。", "8-12 下", "2-3 組", "椅子需靠牆固定，必要時家屬在側方保護。", "sit"],
  ["heel-raise", "扶桌踮腳", "肌力訓練", "下肢|站姿|居家安全", "雙手扶穩桌面，雙腳同時踮起腳跟後慢慢放下，訓練小腿肌力與站立控制。", "保持身體直立，踮腳停留 2 秒，下降時控制速度。", "10-15 下", "2 組", "若有明顯頭暈或足踝疼痛，停止訓練。", "heel"],
  ["seated-march", "坐姿抬膝踏步", "關節活動", "下肢|坐姿|核心", "坐在椅子前半部，左右腳輪流抬膝，提升髖關節活動度與坐姿穩定。", "背部挺直，抬膝高度以不代償後仰為原則，左右交替。", "左右各 10 下", "2 組", "椅子需穩固，避免坐太前方造成滑落。", "seated"],
  ["wall-slide", "牆面手臂上舉", "關節活動", "上肢|肩頸|站姿", "面向牆壁，以手指沿牆面慢慢向上爬，維持肩關節活動度。", "上舉至可忍受範圍停 3 秒，再慢慢放下，避免聳肩代償。", "8-10 下", "2 組", "肩部疼痛超過可忍受範圍時降低高度。", "wall"],
  ["side-step", "扶桌側走", "平衡步態", "下肢|站姿|居家安全", "雙手扶桌或流理台，向左與向右側向移動，練習髖外展肌力與側向平衡。", "腳尖朝前，步幅小而穩，避免身體左右晃動過大。", "左右各 5 趟", "2 組", "地面需清空障礙物，穿止滑鞋。", "side"],
  ["tandem-stance", "前後腳站立", "平衡步態", "下肢|站姿|居家安全", "在桌邊將雙腳前後排列站立，訓練窄底支撐下的靜態平衡。", "先扶桌站穩，再嘗試減少手部支撐，每次維持安全範圍內的秒數。", "每側 20-30 秒", "2-3 回", "需有穩固支撐物，不建議獨自閉眼練習。", "balance"],
  ["reaching-cup", "坐姿取物練習", "日常功能", "上肢|坐姿|核心|ADL", "坐姿下伸手拿取不同方向的杯子或物品，練習上肢控制與軀幹重心轉移。", "物品放在可安全碰到的位置，左右與前方各練習，動作慢而穩。", "每方向 6-8 下", "2 組", "避免過度前伸造成椅子翻覆或滑落。", "reach"],
  ["step-up", "低階踏階", "平衡步態", "下肢|站姿|ADL", "使用低階踏板或樓梯第一階，練習上下階所需肌力與協調。", "一腳踏上、另一腳跟上，再依序退回地面，可扶欄杆或桌邊。", "左右各 6-10 下", "2 組", "踏板需防滑且高度不宜過高。", "step"],
  ["ankle-pump", "踝泵運動", "關節活動", "下肢|臥姿|坐姿", "透過腳踝上下活動促進下肢循環，維持踝關節活動度。", "腳尖向上勾再向下踩，動作連續但不憋氣。", "20 下", "2-3 組", "若小腿劇痛、腫脹或發熱，暫停並回報醫療人員。", "ankle"],
  ["ankle-circle", "踝關節畫圈", "關節活動", "下肢|坐姿|臥姿", "以腳踝畫圈，改善踝關節活動與足部控制。", "順時針與逆時針各畫圈，膝蓋盡量保持穩定。", "每方向 10 圈", "2 組", "動作以舒適範圍為主，避免快速甩動。", "assets/exercises/ankle-circle.png"],
  ["quad-set", "股四頭肌等長收縮", "肌力訓練", "下肢|臥姿", "躺姿或坐姿下將膝窩往床面壓，喚醒大腿前側肌肉。", "腳尖朝上，膝蓋伸直用力 5 秒後放鬆。", "10 下", "2-3 組", "膝蓋疼痛明顯時降低用力程度。", "supineLeg"],
  ["straight-leg-raise", "直膝抬腿", "肌力訓練", "下肢|臥姿|核心", "仰躺時膝蓋伸直抬腿，訓練髖屈肌與股四頭肌。", "一腳彎曲踩床，另一腳伸直抬高約 30 公分後慢慢放下。", "8-12 下", "2 組", "若腰部拱起或疼痛，降低高度或暫停。", "assets/exercises/straight-leg-raise.png"],
  ["short-arc-quad", "短弧膝伸直", "肌力訓練", "下肢|臥姿", "膝下墊毛巾卷，伸直膝蓋訓練大腿前側肌力。", "小腿抬起至膝蓋伸直，停 2 秒後慢放。", "10-15 下", "2 組", "毛巾高度不宜過高，避免膝部不適。", "assets/exercises/short-arc-quad.png"],
  ["long-arc-quad", "坐姿膝伸直", "肌力訓練", "下肢|坐姿", "坐姿下伸直膝蓋，訓練股四頭肌與膝關節控制。", "大腿貼椅面，小腿慢慢伸直至可控制範圍，再慢慢放下。", "10-15 下", "2 組", "避免甩腿，膝蓋疼痛時減少角度。", "assets/exercises/long-arc-quad.png"],
  ["hamstring-curl-standing", "站姿屈膝後勾", "肌力訓練", "下肢|站姿|居家安全", "扶桌站立時將腳跟往臀部方向勾起，訓練大腿後側。", "身體直立，膝蓋朝下，慢慢彎曲再放下。", "左右各 10 下", "2 組", "需扶穩支撐物，避免身體前傾代償。", "assets/exercises/hamstring-curl-standing.png"],
  ["hip-abduction-standing", "站姿髖外展", "肌力訓練", "下肢|站姿|居家安全", "扶桌將腿向側邊打開，訓練臀中肌與側向穩定。", "腳尖朝前，腿向外抬起小角度後慢慢回來。", "左右各 10 下", "2 組", "身體不要側彎，站立腳需穩。", "assets/exercises/hip-abduction-standing.png"],
  ["hip-extension-standing", "站姿髖後伸", "肌力訓練", "下肢|站姿", "扶桌將腿向後伸，訓練臀大肌與站立控制。", "膝蓋保持微伸直，腿向後小幅抬起，不拱腰。", "左右各 10 下", "2 組", "腰痛者減少幅度。", "assets/exercises/hip-extension-standing.png"],
  ["mini-squat", "扶桌半蹲", "肌力訓練", "下肢|站姿|居家安全", "扶穩桌面做小角度蹲下再站起，訓練下肢肌力。", "膝蓋朝腳尖方向，臀部微向後坐，蹲到可控制範圍。", "8-12 下", "2 組", "避免膝蓋內夾或蹲太深。", "assets/exercises/mini-squat.png"],
  ["bridge", "橋式運動", "肌力訓練", "核心|下肢|臥姿", "仰躺屈膝抬起臀部，訓練臀肌與核心穩定。", "腹部微收，臀部抬起至身體成一直線，停 2 秒慢放。", "8-12 下", "2 組", "若腰痛或抽筋，降低高度或暫停。", "bridge"],
  ["clamshell", "側躺蚌殼", "肌力訓練", "下肢|臥姿", "側躺屈膝，將上方膝蓋打開，訓練髖外旋與臀中肌。", "骨盆保持穩定，腳跟相碰，膝蓋慢開慢合。", "左右各 10-15 下", "2 組", "避免身體往後翻。", "assets/exercises/clamshell.png"],
  ["side-lying-leg-raise", "側躺抬腿", "肌力訓練", "下肢|臥姿", "側躺將上方腿抬起，訓練臀中肌與髖部穩定。", "腳尖朝前或微向下，腿抬至可控制高度後慢放。", "左右各 10 下", "2 組", "腰部不適時降低高度。", "assets/exercises/side-lying-leg-raise.png"],
  ["prone-hip-extension", "俯臥髖後伸", "肌力訓練", "下肢|臥姿", "俯臥抬起單側大腿，訓練臀肌與髖伸直能力。", "膝蓋可微彎，腿離床小幅度即可，不用力拱腰。", "左右各 8-10 下", "2 組", "腰椎不適者需治療師確認後執行。", "assets/exercises/prone-hip-extension.png"],
  ["toe-raise", "扶桌抬腳尖", "肌力訓練", "下肢|站姿|居家安全", "扶桌站立抬起腳尖，訓練脛前肌與步態清腳能力。", "腳跟留在地面，腳尖向上抬，再慢慢放下。", "10-15 下", "2 組", "站立不穩者可改坐姿。", "assets/exercises/toe-raise.png"],
  ["seated-heel-raise", "坐姿踮腳", "肌力訓練", "下肢|坐姿", "坐姿下抬起腳跟，訓練小腿肌群與足踝控制。", "腳掌前端留在地面，腳跟抬高後慢放。", "15-20 下", "2 組", "足底疼痛時減少次數。", "assets/exercises/seated-heel-raise.png"],
  ["seated-toe-raise", "坐姿抬腳尖", "肌力訓練", "下肢|坐姿", "坐姿下腳跟著地抬腳尖，訓練足踝背屈。", "腳尖抬起停 1 秒，再慢慢放下。", "15-20 下", "2 組", "避免膝蓋跟著晃動。", "assets/exercises/seated-toe-raise.png"],
  ["calf-stretch-wall", "靠牆小腿伸展", "伸展放鬆", "下肢|站姿", "利用牆面伸展小腿後側，改善踝背屈與步態。", "前腳彎、後腳伸直，後腳跟貼地，身體向牆移動。", "20-30 秒", "2-3 回", "避免彈震，足踝疼痛時縮短時間。", "assets/exercises/calf-stretch-wall.png"],
  ["hamstring-stretch-seated", "坐姿腿後肌伸展", "伸展放鬆", "下肢|坐姿", "坐姿伸直一腳，身體微前傾伸展大腿後側。", "背部保持延伸，從髖部前傾到有拉伸感即可。", "20-30 秒", "2-3 回", "避免含胸硬拉或造成坐骨神經痛。", "assets/exercises/hamstring-stretch-seated.png"],
  ["hip-flexor-stretch", "髖屈肌伸展", "伸展放鬆", "下肢|站姿", "站姿或弓箭步伸展髖前側，改善步幅與站姿。", "骨盆微後傾，後腳髖部向前送到有拉伸感。", "20 秒", "2 回", "需扶穩支撐物，避免腰椎過伸。", "assets/exercises/hip-flexor-stretch.png"],
  ["piriformis-stretch", "梨狀肌伸展", "伸展放鬆", "下肢|臥姿|坐姿", "伸展臀部深層肌群，協助髖部活動與坐姿舒適。", "將腳踝跨到對側膝上，身體微前傾或抱腿靠近。", "20-30 秒", "2 回", "髖關節置換或疼痛者需先確認限制。", "assets/exercises/piriformis-stretch.png"],
  ["trunk-rotation-supine", "仰躺軀幹旋轉", "關節活動", "核心|臥姿|腰背", "仰躺屈膝左右倒腿，活動腰椎與軀幹旋轉。", "雙膝併攏慢慢倒向一側，再回中間換邊。", "左右各 8-10 下", "2 組", "動作應溫和，避免疼痛端點硬推。", "assets/exercises/trunk-rotation-supine.png"],
  ["pelvic-tilt", "骨盆前後傾", "核心訓練", "核心|臥姿|腰背", "練習骨盆控制與腹部啟動，常用於腰背復健。", "仰躺屈膝，輕壓腰部貼床再放鬆，配合自然呼吸。", "10-15 下", "2 組", "避免憋氣或用力過猛。", "assets/exercises/pelvic-tilt.png"],
  ["dead-bug-arms", "死蟲式手腳預備", "核心訓練", "核心|臥姿|神經", "仰躺抬起手腳做小範圍交替，訓練核心與協調。", "腹部微收，單手或單腳慢慢移動，腰部維持穩定。", "左右各 6-8 下", "2 組", "腰部離床或疼痛時降低難度。", "assets/exercises/dead-bug-arms.png"],
  ["seated-trunk-flexion", "坐姿軀幹前彎回正", "核心訓練", "核心|坐姿|ADL", "坐姿練習身體前彎與回正，提升轉位前的重心控制。", "雙腳踩穩，身體微向前再回到挺直坐姿。", "8-12 下", "2 組", "避免頭暈，必要時有人在旁保護。", "assets/exercises/seated-trunk-flexion.png"],
  ["seated-lateral-weight-shift", "坐姿左右重心轉移", "核心訓練", "核心|坐姿|神經", "坐姿左右移動重心，訓練軀幹控制與坐姿平衡。", "雙腳踩地，身體慢慢往左右移動後回中線。", "左右各 10 下", "2 組", "避免移動過大造成滑落。", "assets/exercises/seated-lateral-weight-shift.png"],
  ["seated-forward-reach", "坐姿前方伸手", "日常功能", "上肢|坐姿|核心|ADL", "坐姿向前伸手碰觸目標物，練習前方取物與軀幹控制。", "目標放在安全距離，伸手碰到後回正。", "8-10 下", "2 組", "椅子需穩固，避免過度前伸。", "assets/exercises/seated-forward-reach.png"],
  ["seated-cross-body-reach", "坐姿跨中線取物", "日常功能", "上肢|坐姿|核心|神經", "伸手跨過身體中線取物，練習軀幹旋轉與注意力。", "物品放在對側安全距離，伸手拿取後放回。", "左右各 6-8 下", "2 組", "肩痛或失衡時縮短距離。", "assets/exercises/seated-cross-body-reach.png"],
  ["standing-weight-shift", "站姿左右重心轉移", "平衡步態", "下肢|站姿|居家安全", "扶桌站立，左右移動重心，訓練站立承重與平衡。", "雙腳與肩同寬，重心慢移到一腳再回中線。", "左右各 10 下", "2 組", "需扶穩，避免膝蓋鎖死。", "assets/exercises/standing-weight-shift.png"],
  ["standing-forward-back-shift", "站姿前後重心轉移", "平衡步態", "下肢|站姿|居家安全", "在安全支撐旁練習前後移動重心，改善姿勢控制。", "腳掌保持貼地，身體像整體一樣前後微移。", "10-15 下", "2 組", "避免腳跟或腳尖離地過多。", "assets/exercises/standing-forward-back-shift.png"],
  ["single-leg-stance-supported", "扶桌單腳站", "平衡步態", "下肢|站姿|居家安全", "扶桌抬起一腳短暫站立，訓練單腳承重和平衡。", "先雙手扶穩，再抬腳 3-10 秒，左右交替。", "每側 5-8 回", "2 組", "不建議無支撐獨自練習。", "assets/exercises/single-leg-stance-supported.png"],
  ["marching-standing", "扶桌原地踏步", "平衡步態", "下肢|站姿|居家安全", "扶桌原地交替抬膝，練習步態節奏與單腳承重。", "抬膝高度以穩定為主，左右交替慢速進行。", "左右各 10 下", "2 組", "頭暈或不穩時立即坐下休息。", "assets/exercises/marching-standing.png"],
  ["backward-walking-supported", "扶桌後退走", "平衡步態", "步態|下肢|居家安全", "沿桌邊小步後退，訓練後向步態與空間控制。", "手扶穩，腳尖先找地，小步慢退。", "3-5 趟", "2 組", "確保後方無障礙物。", "assets/exercises/backward-walking-supported.png"],
  ["forward-walking-line", "直線步行", "平衡步態", "步態|下肢|站姿", "沿地面直線慢走，訓練步態對稱與方向控制。", "眼睛看前方，步伐穩定，必要時靠近牆面。", "5-10 公尺", "2-3 趟", "跌倒風險高者需陪同。", "assets/exercises/forward-walking-line.png"],
  ["tandem-walk-supported", "扶牆前後腳走", "平衡步態", "步態|下肢|居家安全", "沿牆或扶手做前後腳步行，提升動態平衡。", "一腳腳跟接近另一腳腳尖，小步慢行。", "3-5 公尺", "2 趟", "需有扶手或家屬保護。", "assets/exercises/tandem-walk-supported.png"],
  ["turning-practice", "原地轉身練習", "平衡步態", "步態|站姿|居家安全", "練習分段轉身，降低轉彎時跌倒風險。", "用多個小步慢慢轉向，不交叉腳，不急轉。", "左右各 3-5 次", "2 組", "地面需清空，避免頭暈。", "assets/exercises/turning-practice.png"],
  ["sit-pivot-transfer", "坐姿移位轉位", "日常功能", "ADL|坐姿|核心", "在椅面上練習臀部小幅挪動，準備床椅轉位。", "雙腳踩穩，身體前傾，臀部向左或右小幅移動。", "左右各 5 次", "2 組", "椅子需固定，必要時治療師指導。", "assets/exercises/sit-pivot-transfer.png"],
  ["bed-rolling", "床上翻身訓練", "日常功能", "ADL|臥姿|核心", "練習在床上由仰躺翻向側躺，提升床上活動能力。", "彎膝、手帶動身體轉向，分段完成翻身。", "左右各 5 次", "2 組", "床邊需安全，避免翻落。", "bedRoll"],
  ["supine-to-sit", "躺到坐起訓練", "日常功能", "ADL|核心|臥姿", "練習由躺姿轉為坐姿，提升起床獨立性。", "先側躺，雙腳移到床邊，以手推床坐起。", "5-8 次", "2 組", "避免直接仰臥硬坐造成腰痛。", "supineSit"],
  ["chair-push-up", "椅上撐起減壓", "肌力訓練", "上肢|坐姿|ADL", "坐在有扶手椅上用手撐起臀部，訓練上肢與減壓能力。", "手握扶手，肩膀下壓，臀部微離椅面後慢放。", "5-8 下", "2 組", "椅子需穩固，有肩痛者避免。", "assets/exercises/chair-push-up.png"],
  ["scapular-squeeze", "肩胛後收", "肌力訓練", "上肢|肩頸|坐姿", "坐姿或站姿將肩胛骨往後夾，改善姿勢與肩帶控制。", "肩膀放鬆不聳肩，肩胛向後下方收 3 秒。", "10-15 下", "2 組", "避免憋氣或過度挺胸。", "assets/exercises/scapular-squeeze.png"],
  ["shoulder-pendulum", "肩關節鐘擺", "關節活動", "上肢|肩頸|站姿", "身體微前傾讓手臂自然擺動，常用於肩部放鬆。", "扶桌支撐，手臂放鬆做前後、左右或小圈擺動。", "30 秒", "2-3 回", "急性疼痛或術後限制需依醫囑。", "assets/exercises/shoulder-pendulum.png"],
  ["shoulder-flexion-cane", "棍棒輔助肩屈曲", "關節活動", "上肢|肩頸|臥姿", "用健側帶動患側手臂上舉，維持肩屈曲活動。", "雙手握棍，慢慢往頭上方向帶到可忍受範圍。", "8-10 下", "2 組", "避免疼痛硬推或聳肩。", "assets/exercises/shoulder-flexion-cane.png"],
  ["shoulder-external-rotation-cane", "棍棒肩外旋", "關節活動", "上肢|肩頸|坐姿", "手肘靠身體，以棍棒協助肩外旋活動。", "患側手肘彎 90 度貼身，健側推棍讓前臂向外。", "8-10 下", "2 組", "術後個案需確認外旋角度限制。", "assets/exercises/shoulder-external-rotation-cane.png"],
  ["table-slide-flexion", "桌面滑手前伸", "關節活動", "上肢|坐姿|肩頸", "坐在桌前讓手在桌面向前滑，增加肩屈曲活動。", "手放毛巾上，身體微前傾協助手臂滑遠，再回來。", "10 下", "2 組", "肩痛時縮短距離。", "assets/exercises/table-slide-flexion.png"],
  ["table-slide-abduction", "桌面滑手外展", "關節活動", "上肢|坐姿|肩頸", "手在桌面向側邊滑動，維持肩外展活動。", "手放毛巾上，慢慢往側邊滑到舒適範圍。", "8-10 下", "2 組", "避免聳肩或身體歪斜代償。", "assets/exercises/table-slide-abduction.png"],
  ["elbow-flex-extension", "手肘彎伸", "關節活動", "上肢|坐姿", "坐姿下手肘彎曲與伸直，維持肘關節活動。", "手掌向上或中立，慢慢彎手肘再伸直。", "10-15 下", "2 組", "若術後或骨折需依限制角度。", "assets/exercises/elbow-flex-extension.png"],
  ["forearm-pronation-supination", "前臂旋前旋後", "關節活動", "上肢|坐姿|手功能", "前臂放桌上，手掌向上向下翻轉，維持旋轉活動。", "手肘彎 90 度貼近身體，慢慢翻掌。", "左右各 10 下", "2 組", "避免手腕代償過多。", "hand"],
  ["wrist-flex-extension", "手腕彎伸", "關節活動", "上肢|坐姿|手功能", "前臂支撐在桌上，做手腕彎曲與伸直活動。", "手腕慢慢往上翹再往下彎，保持前臂穩定。", "10-15 下", "2 組", "腕部疼痛時減少角度。", "assets/exercises/wrist-flex-extension.png"],
  ["wrist-radial-ulnar", "手腕左右偏移", "關節活動", "上肢|坐姿|手功能", "手腕左右移動，維持橈尺偏活動。", "手掌朝下放桌邊或毛巾上，左右慢慢移動。", "10-15 下", "2 組", "避免快速甩動。", "assets/exercises/wrist-radial-ulnar.png"],
  ["finger-tendon-glide", "手指肌腱滑動", "上肢手功能", "上肢|手功能|坐姿", "依序做直手、鉤拳、平拳、全拳，改善手指滑動。", "每個姿勢停 2 秒，動作慢且完整。", "5-10 輪", "2 組", "術後或腫脹者以治療師指示為準。", "assets/exercises/finger-tendon-glide.png"],
  ["thumb-opposition", "拇指對指", "上肢手功能", "上肢|手功能|坐姿", "拇指依序碰食指到小指，訓練精細動作。", "每次碰到指腹後張開手，再換下一指。", "每指 5-10 下", "2 組", "避免用力捏造成疼痛。", "assets/exercises/thumb-opposition.png"],
  ["finger-spread", "手指張開併攏", "上肢手功能", "上肢|手功能|坐姿", "手掌放桌上，手指張開再併攏，訓練手內在肌。", "手指盡量平貼桌面，慢慢打開再合回。", "10-15 下", "2 組", "若有關節疼痛，降低幅度。", "assets/exercises/finger-spread.png"],
  ["grip-towel", "毛巾握力訓練", "上肢手功能", "上肢|手功能|ADL", "握毛巾或軟球，訓練手部握力。", "握緊 3 秒後放鬆，力量以不痛為原則。", "10 下", "2 組", "避免使用過硬器材造成手痛。", "assets/exercises/grip-towel.png"],
  ["pinch-clip", "曬衣夾捏力", "上肢手功能", "上肢|手功能|ADL", "用拇指與食指或中指按壓曬衣夾，訓練捏力。", "慢慢打開夾子再放鬆，可左右手分別練習。", "8-12 下", "2 組", "手指關節腫痛時降低次數。", "assets/exercises/pinch-clip.png"],
  ["peg-transfer", "插棒移位", "上肢手功能", "上肢|手功能|神經", "將小棒或棋子從一處移到另一處，訓練精細協調。", "一次拿一個，保持坐姿穩定，注重準確度。", "10-20 個", "1-2 回", "物品大小需符合吞食安全與能力。", "assets/exercises/peg-transfer.png"],
  ["coin-pickup", "硬幣撿拾", "上肢手功能", "上肢|手功能|ADL", "從桌面撿起硬幣或鈕扣，練習指尖控制。", "慢慢捏起並放入杯中，可由大物件進階到小物件。", "10 個", "2 回", "視力或認知不佳者需有人看顧。", "assets/exercises/coin-pickup.png"],
  ["cloth-folding", "摺毛巾訓練", "日常功能", "上肢|ADL|坐姿", "練習將毛巾攤平、對折與整理，訓練雙手協調。", "坐在桌前，以雙手完成攤平與折疊。", "3-5 條", "1-2 回", "避免肩膀過度疲勞。", "towel"],
  ["cup-to-mouth", "杯子拿取到口", "日常功能", "上肢|ADL|坐姿", "模擬喝水動作，訓練肩肘腕協調與自我照顧。", "拿起空杯或少量水杯，移到嘴邊再放回桌面。", "8-10 下", "2 組", "吞嚥或手抖明顯者需陪同。", "spoon"],
  ["spoon-scoop", "湯匙舀取練習", "日常功能", "上肢|手功能|ADL", "用湯匙舀豆子或乾米，訓練進食動作與手腕控制。", "從一個碗舀到另一個碗，速度慢且穩。", "10-20 次", "1-2 回", "使用乾材料較安全，避免燙食。", "assets/exercises/spoon-scoop.png"],
  ["button-board", "扣鈕扣練習", "日常功能", "手功能|ADL|坐姿", "使用衣物或練習板扣鈕扣，訓練穿衣精細動作。", "由大鈕扣開始，完成扣上與解開。", "5-10 顆", "1-2 回", "挫折或疲勞時休息，逐步增加難度。", "button"],
  ["zipper-practice", "拉鍊練習", "日常功能", "手功能|ADL|坐姿", "練習拉鍊插入、拉上與拉下，提升穿衣獨立性。", "衣物固定在桌上或身上，先慢慢對準再拉動。", "5-8 次", "1-2 回", "手部疼痛時選用大拉環。", "zipper"],
  ["reacher-practice", "取物夾使用", "日常功能", "ADL|上肢|居家安全", "使用取物夾拿取地面或遠端物品，降低彎腰跌倒風險。", "坐姿或站姿使用取物夾夾起輕物並放到桌上。", "8-12 個", "1-2 回", "站姿操作需注意平衡。", "reacher"],
  ["sock-aid-practice", "穿襪輔具練習", "日常功能", "ADL|坐姿|下肢", "使用穿襪輔具練習下肢穿著，提升自我照顧。", "坐穩後將襪子套在輔具上，拉繩將襪子穿上。", "3-5 次", "1-2 回", "髖關節限制者需遵守醫囑角度。", "assets/exercises/sock-aid-practice.png"],
  ["breathing-diaphragmatic", "腹式呼吸", "呼吸耐力", "耐力|坐姿|臥姿", "透過腹部起伏訓練橫膈呼吸，協助放鬆與換氣。", "一手放胸一手放腹，吸氣腹部微鼓，吐氣放鬆。", "5-10 分鐘", "1-2 回", "若呼吸困難或胸悶需停止。", "breathing"],
  ["pursed-lip-breathing", "噘嘴吐氣", "呼吸耐力", "耐力|坐姿", "用鼻吸氣、噘嘴慢吐，協助控制呼吸節奏。", "吸氣 2 秒，噘嘴吐氣 4 秒，肩頸放鬆。", "5 分鐘", "1-2 回", "頭暈時暫停並自然呼吸。", "assets/exercises/pursed-lip-breathing.png"],
  ["thoracic-expansion", "胸廓擴張呼吸", "呼吸耐力", "耐力|坐姿|肩頸", "配合手臂外展或胸廓擴張，改善胸腔活動。", "吸氣時胸廓打開，吐氣時手臂回到身側。", "8-10 下", "2 組", "肩痛者可只做呼吸不抬手。", "assets/exercises/thoracic-expansion.png"],
  ["seated-arm-swing", "坐姿擺手耐力", "呼吸耐力", "耐力|上肢|坐姿", "坐姿交替擺手，作為低強度心肺耐力活動。", "保持背部挺直，雙手自然前後擺動。", "1-3 分鐘", "2 回", "可用說話測試調整強度。", "assets/exercises/seated-arm-swing.png"],
  ["walking-program", "室內步行計畫", "呼吸耐力", "耐力|步態|居家安全", "在安全室內路線進行定時步行，提升耐力與日常活動量。", "以可說話但微喘的速度行走，記錄時間與疲勞程度。", "3-10 分鐘", "1-3 回", "需移除地面障礙，必要時陪同。", "assets/exercises/walking-program.png"],
  ["step-tap", "踏板點踩", "平衡步態", "下肢|站姿|居家安全", "扶穩支撐物，單腳點上低踏板再回地面，訓練重心轉移。", "左右腳輪流點踩，身體保持直立。", "左右各 8-10 下", "2 組", "踏板需穩固防滑。", "assets/exercises/step-tap.png"],
  ["lateral-step-up", "側向踏階", "平衡步態", "下肢|站姿|ADL", "從側邊踏上低階，訓練側向肌力與樓梯能力。", "手扶欄杆，側身一腳踏上再回地面。", "左右各 6-8 下", "2 組", "膝蓋需朝腳尖方向。", "assets/exercises/lateral-step-up.png"],
  ["stair-descent-practice", "下階控制練習", "平衡步態", "下肢|步態|居家安全", "練習從低階慢慢下踩，改善離心控制與下樓安全。", "手扶欄杆，一腳慢慢下到地面，再回起始姿勢。", "左右各 5-8 下", "2 組", "需有治療師或家屬確認安全。", "assets/exercises/stair-descent-practice.png"],
  ["wall-push-up", "牆壁伏地挺身", "肌力訓練", "上肢|站姿|肩頸", "站在牆前做伏地挺身，訓練上肢推撐能力。", "雙手扶牆，身體成一直線，彎手肘靠近牆再推回。", "8-12 下", "2 組", "肩痛或手腕痛時降低幅度。", "wallPush"],
  ["counter-push-up", "桌邊伏地挺身", "肌力訓練", "上肢|站姿|ADL", "扶穩桌邊做斜面推撐，提升上肢與核心力量。", "手扶桌邊，身體直線，彎肘下降再推回。", "8-10 下", "2 組", "桌子需穩固不滑動。", "assets/exercises/counter-push-up.png"],
  ["theraband-row", "彈力帶划船", "肌力訓練", "上肢|肩頸|坐姿", "使用彈力帶向後拉，訓練背部與肩胛穩定。", "手肘貼近身體向後拉，肩胛向後下收。", "10-15 下", "2 組", "彈力帶固定點需安全。", "band"],
  ["theraband-external-rotation", "彈力帶肩外旋", "肌力訓練", "上肢|肩頸|坐姿", "手肘貼身拉彈力帶外旋，訓練旋轉肌袖。", "手肘彎 90 度夾毛巾，前臂向外拉再慢回。", "8-12 下", "2 組", "避免肩膀聳起或疼痛硬拉。", "assets/exercises/theraband-external-rotation.png"],
  ["biceps-curl", "坐姿二頭肌彎舉", "肌力訓練", "上肢|坐姿", "使用水瓶或小啞鈴做手肘彎曲，訓練上肢拿取能力。", "手掌朝上，手肘靠身體慢慢彎起再放下。", "10-12 下", "2 組", "重量以可控制且不痛為準。", "assets/exercises/biceps-curl.png"],
  ["triceps-extension", "坐姿手肘伸直推壓", "肌力訓練", "上肢|坐姿", "以彈力帶或輕重量訓練三頭肌，幫助推撐與轉位。", "手肘彎曲後慢慢伸直，保持肩膀穩定。", "8-12 下", "2 組", "肩肘疼痛時降低阻力。", "assets/exercises/triceps-extension.png"],
  ["overhead-reach-light", "輕物上舉放置", "日常功能", "上肢|站姿|ADL", "將輕物放到較高層架，練習日常置物與肩部控制。", "拿輕物從桌面移到肩高附近架面，再放回。", "6-8 下", "2 組", "避免超過疼痛角度或拿重物。", "assets/exercises/overhead-reach-light.png"],
  ["laundry-basket-lift", "洗衣籃抬放", "日常功能", "ADL|下肢|核心", "模擬搬移輕洗衣籃，訓練蹲站與雙手持物。", "靠近物品、屈髖屈膝，雙手拿起輕籃再放回。", "5-8 下", "2 組", "重量需很輕，避免彎腰硬拉。", "assets/exercises/laundry-basket-lift.png"],
  ["counter-reaching-standing", "站姿流理台取物", "日常功能", "ADL|站姿|上肢", "站在流理台前拿取左右物品，訓練站姿功能性伸手。", "一手可扶桌，另一手拿取安全距離內物品。", "左右各 8 下", "2 組", "不穩者改坐姿或家屬保護。", "assets/exercises/counter-reaching-standing.png"],
  ["kitchen-task-sequence", "廚房任務排序", "日常功能", "ADL|站姿|神經", "依序完成拿杯、倒水、放回等簡短任務，訓練認知與動作整合。", "先口頭確認步驟，再慢慢完成 2-4 個步驟。", "3-5 輪", "1 回", "避免熱水與尖銳物。", "scanning"],
  ["visual-scanning-reaching", "視覺掃描取物", "神經復能", "神經|上肢|坐姿", "在桌面不同位置尋找並拿取物品，訓練視覺掃描與注意力。", "從左到右掃描，看到目標後伸手拿取並放入盒中。", "10-20 個", "1-2 回", "忽略症個案可加明顯提示。", "assets/exercises/visual-scanning-reaching.png"],
  ["mirror-arm-movement", "鏡像手臂活動", "神經復能", "神經|上肢|坐姿", "利用健側手臂動作與鏡像回饋，促進患側動作意象。", "患側放鏡後，健側慢慢做手腕或手指動作並觀察鏡像。", "5-10 分鐘", "1 回", "需治療師教導擺位。", "assets/exercises/mirror-arm-movement.png"],
  ["bilateral-arm-lift", "雙手交握上舉", "神經復能", "神經|上肢|坐姿", "雙手交握由健側協助患側上舉，維持上肢活動。", "手指交握，慢慢往前上方抬到舒適範圍再放下。", "8-10 下", "2 組", "肩關節半脫位或疼痛需先確認。", "bilateralArm"],
  ["weight-bearing-hand-table", "手掌桌面承重", "神經復能", "神經|上肢|坐姿", "坐姿將手掌放桌面輕承重，促進上肢本體感覺。", "手掌張開放穩，身體微向該側移動後回中線。", "左右各 8 下", "2 組", "手腕疼痛或肩不穩時需調整。", "assets/exercises/weight-bearing-hand-table.png"],
  ["reaching-cone-stack", "杯錐堆疊", "神經復能", "神經|上肢|坐姿", "拿取並堆疊杯錐，訓練伸手、抓握與放置控制。", "一次拿一個杯錐，堆高或左右移位。", "10-15 個", "1-2 回", "物品高度需避免肩痛。", "assets/exercises/reaching-cone-stack.png"],
  ["sit-balance-ball-toss", "坐姿拋接球", "神經復能", "神經|坐姿|核心", "坐姿下拋接輕球，訓練反應、雙手協調與坐姿平衡。", "使用軟球，距離短，接球後回到正中姿勢。", "10-20 次", "1-2 回", "坐姿不穩者需在旁保護。", "ball"],
  ["standing-balloon-tap", "站姿拍氣球", "平衡步態", "站姿|上肢|神經", "站姿輕拍氣球，訓練動態平衡與反應。", "站在桌邊或家屬旁，輕拍氣球並維持站穩。", "30-60 秒", "2 回", "跌倒風險高者改坐姿。", "assets/exercises/standing-balloon-tap.png"],
  ["dual-task-walk", "雙重任務步行", "神經復能", "步態|神經|耐力", "步行同時進行簡單認知任務，訓練社區步行能力。", "安全路線中邊走邊數數或命名物品，速度放慢。", "3-5 分鐘", "1-2 回", "需先確認單純步行安全。", "assets/exercises/dual-task-walk.png"],
  ["obstacle-step-over", "跨越低障礙", "平衡步態", "步態|下肢|居家安全", "跨過低軟障礙物，練習清腳與步態適應。", "扶穩或有人保護，慢慢跨過低障礙再回來。", "5-8 次", "2 組", "障礙物需柔軟且高度低。", "threshold"],
  ["floor-pickup-safe", "安全撿物訓練", "日常功能", "ADL|下肢|居家安全", "練習用安全策略從地面撿起物品，降低跌倒風險。", "靠近穩固支撐，一手扶穩，屈膝或使用取物夾拿物。", "5-8 次", "1-2 回", "頭暈、骨鬆或術後者需個別評估。", "assets/exercises/floor-pickup-safe.png"],
  ["car-transfer-sim", "上下車轉位模擬", "日常功能", "ADL|下肢|坐姿", "模擬坐入車座與雙腳移入車內，訓練社區活動。", "先坐穩再移動雙腳，必要時使用塑膠袋輔助旋轉。", "3-5 次", "1-2 回", "需在安全座椅高度下練習。", "assets/exercises/car-transfer-sim.png"],
  ["toilet-transfer", "馬桶轉位練習", "日常功能", "ADL|下肢|居家安全", "練習靠近、轉身、坐下與站起，提升如廁安全。", "使用扶手或穩固支撐，分段完成轉身與坐站。", "5 次", "1-2 回", "浴廁濕滑需特別注意防滑。", "toiletTransfer"],
  ["shower-step-entry", "浴室門檻跨步", "日常功能", "ADL|下肢|居家安全", "練習跨越低門檻或浴室入口，提升洗澡安全。", "扶穩支撐，先抬一腳跨入，再另一腳跟進。", "5-8 次", "1-2 回", "地面需乾燥防滑，必要時陪同。", "assets/exercises/shower-step-entry.png"],
  ["bedside-standing-tolerance", "床邊站立耐受", "呼吸耐力", "耐力|站姿|居家安全", "在床邊或桌邊安全站立，建立站姿耐受與下肢承重。", "雙腳站穩，手扶支撐，維持可接受時間。", "30 秒-3 分鐘", "2-3 回", "頭暈或血壓不穩時停止。", "assets/exercises/bedside-standing-tolerance.png"],
  ["seated-posture-reset", "坐姿姿勢重整", "伸展放鬆", "坐姿|肩頸|核心", "坐姿調整骨盆、胸椎與肩頸，降低久坐不適。", "坐骨平均承重，胸口微開，肩膀放鬆，維持自然呼吸。", "30-60 秒", "3 回", "避免刻意挺腰造成疼痛。", "neck"],
  ["chin-tuck", "下巴內收", "伸展放鬆", "肩頸|坐姿", "輕做下巴內收，改善頭頸姿勢與深頸屈肌控制。", "眼睛看前方，下巴水平向後收，像做雙下巴。", "8-10 下", "2 組", "不可用力低頭或造成暈眩。", "assets/exercises/chin-tuck.png"],
  ["upper-trap-stretch", "上斜方肌伸展", "伸展放鬆", "肩頸|坐姿", "坐姿側彎頭部伸展頸肩上方肌群。", "一手可扶椅，頭慢慢側彎到有拉伸感。", "20 秒", "2 回", "避免拉到麻痛或暈眩。", "assets/exercises/upper-trap-stretch.png"],
  ["levator-scap-stretch", "提肩胛肌伸展", "伸展放鬆", "肩頸|坐姿", "頭轉向斜下方伸展後頸側肌群。", "看向腋下方向，輕微低頭至有拉伸感。", "20 秒", "2 回", "手不要硬拉頭部。", "assets/exercises/levator-scap-stretch.png"],
  ["thoracic-extension-chair", "椅背胸椎伸展", "伸展放鬆", "腰背|坐姿|肩頸", "坐姿靠椅背做胸椎伸展，改善駝背與胸廓活動。", "雙手抱胸或扶頭，胸椎靠椅背輕輕往後伸。", "8-10 下", "2 組", "避免腰椎過度後仰。", "assets/exercises/thoracic-extension-chair.png"],
  ["cat-camel", "貓牛式", "關節活動", "腰背|核心|臥姿", "四足跪姿做脊椎彎曲與伸展，維持脊椎活動。", "背部慢慢拱起再放鬆下沉，配合呼吸。", "8-10 下", "2 組", "手腕或膝蓋痛者需墊軟墊或改姿勢。", "assets/exercises/cat-camel.png"],
  ["child-pose-modified", "改良嬰兒式伸展", "伸展放鬆", "腰背|肩頸|臥姿", "跪姿或坐姿向前伸手，放鬆背部與肩膀。", "手向前滑，臀部往後坐到舒適範圍。", "20-30 秒", "2 回", "膝蓋不適者改坐姿桌面前伸。", "assets/exercises/child-pose-modified.png"],
  ["standing-back-extension", "站姿腰部後伸", "關節活動", "腰背|站姿", "雙手扶腰做小幅後伸，活動腰椎並中斷久坐。", "站穩後骨盆輕推前，胸口微開，小幅後伸。", "5-8 下", "1-2 組", "下肢麻痛加劇時停止。", "assets/exercises/standing-back-extension.png"],
  ["wall-posture-check", "靠牆姿勢檢查", "日常功能", "站姿|肩頸|核心", "背靠牆感受頭、肩、骨盆排列，建立站姿覺察。", "後腦、上背與臀部接近牆面，維持自然呼吸。", "30 秒", "3 回", "不需強迫腰部貼牆。", "assets/exercises/wall-posture-check.png"],
  ["seated-ball-squeeze", "坐姿夾球", "肌力訓練", "下肢|坐姿|核心", "坐姿膝間夾軟球或枕頭，訓練髖內收與坐姿穩定。", "雙膝輕夾 5 秒後放鬆，保持背部挺直。", "10 下", "2 組", "髖或膝痛者降低力量。", "assets/exercises/seated-ball-squeeze.png"],
  ["seated-band-abduction", "坐姿彈力帶開膝", "肌力訓練", "下肢|坐姿", "坐姿膝上套彈力帶，雙膝向外打開訓練臀肌。", "腳踩地，膝蓋慢慢外開再控制回來。", "10-15 下", "2 組", "彈力帶阻力不宜過強。", "assets/exercises/seated-band-abduction.png"],
  ["seated-row-towel", "毛巾划船", "肌力訓練", "上肢|坐姿|肩頸", "雙手拉毛巾做划船感，訓練肩胛後收與姿勢。", "雙手握毛巾，手肘向後拉，肩膀放鬆。", "10-15 下", "2 組", "避免聳肩和憋氣。", "assets/exercises/seated-row-towel.png"],
  ["medicine-ball-trunk-rotation", "坐姿抱球轉體", "核心訓練", "核心|坐姿|上肢", "抱輕球左右轉體，訓練軀幹旋轉與雙手協調。", "坐穩後球在胸前，身體慢慢轉向左右。", "左右各 8 下", "2 組", "腰痛或頭暈時降低角度。", "assets/exercises/medicine-ball-trunk-rotation.png"],
  ["standing-reaching-clock", "站姿時鐘伸手", "平衡步態", "站姿|上肢|居家安全", "想像前方時鐘方向伸手，訓練站姿動態平衡。", "一手扶穩，另一手向 12、3、6、9 點方向伸出。", "每方向 5 下", "2 組", "伸手距離不超過安全範圍。", "assets/exercises/standing-reaching-clock.png"],
  ["foam-surface-stance", "軟墊站立", "平衡步態", "站姿|下肢|居家安全", "站在軟墊上訓練本體感覺與姿勢控制。", "雙手靠近支撐物，雙腳站穩維持平衡。", "20-30 秒", "2-3 回", "僅限治療師評估安全後執行。", "assets/exercises/foam-surface-stance.png"],
  ["narrow-base-stance", "窄站姿平衡", "平衡步態", "站姿|下肢|居家安全", "雙腳併攏或靠近站立，訓練靜態平衡。", "站在桌邊，雙腳靠近，嘗試減少手部支撐。", "20-30 秒", "2-3 回", "不穩時立即扶桌。", "assets/exercises/narrow-base-stance.png"],
  ["head-turn-standing", "站姿轉頭平衡", "平衡步態", "站姿|神經|居家安全", "站立時左右轉頭，訓練前庭與姿勢控制。", "扶桌站穩後，頭慢慢左右轉動，眼睛看目標。", "左右各 5 下", "2 組", "頭暈者需停止並坐下。", "assets/exercises/head-turn-standing.png"],
  ["gaze-stabilization-seated", "坐姿凝視穩定", "神經復能", "神經|坐姿|肩頸", "眼睛看固定目標，頭部小幅轉動，訓練凝視穩定。", "拇指或目標放眼前，眼睛盯住目標，頭慢慢左右轉。", "20-30 秒", "2-3 回", "暈眩加劇時停止。", "assets/exercises/gaze-stabilization-seated.png"],
  ["metronome-stepping", "節拍踏步", "神經復能", "步態|神經|下肢", "配合節拍器或口令踏步，訓練步態節奏。", "扶穩支撐，跟著節拍左右交替踏步。", "30-60 秒", "2 回", "速度由慢開始，避免追節拍而失衡。", "assets/exercises/metronome-stepping.png"],
  ["large-amplitude-reaching", "大幅度伸手訓練", "神經復能", "神經|上肢|站姿", "以較大但安全的動作伸手，提升動作幅度與速度。", "站或坐姿向前、側方大幅伸手，再回到起始姿勢。", "每方向 6-8 下", "2 組", "需依平衡能力選擇坐姿或站姿。", "assets/exercises/large-amplitude-reaching.png"],
  ["floor-to-stand-prep", "地板起身預備", "日常功能", "ADL|下肢|居家安全", "練習由高跪、半跪到扶物站起的部分動作。", "在軟墊旁靠穩固家具，分段練習半跪承重。", "3-5 次", "1-2 回", "需治療師確認安全，不適合高跌倒風險者獨練。", "assets/exercises/floor-to-stand-prep.png"],
  ["home-entry-walking", "門口進出步行", "日常功能", "步態|ADL|居家安全", "模擬從室內走到門口並轉身回來，訓練實際動線。", "沿熟悉路線走到門口，分段轉身後走回座位。", "2-4 趟", "1-2 回", "門檻與鞋子需先確認安全。", "assets/exercises/home-entry-walking.png"],
  ["carry-light-object-walk", "持輕物步行", "日常功能", "步態|ADL|上肢", "拿輕物短距離步行，練習日常搬運與步態穩定。", "雙手或單手拿輕物，慢走到指定位置再放下。", "3-5 趟", "1-2 回", "先確認空手步行穩定，物品不可遮擋視線。", "assets/exercises/carry-light-object-walk.png"]
];

window.exerciseCategories = ["全部", "關節活動", "肌力訓練", "核心訓練", "平衡步態", "日常功能", "上肢手功能", "神經復能", "呼吸耐力", "伸展放鬆"];
window.exerciseTags = ["上肢", "下肢", "核心", "居家安全", "坐姿", "站姿", "臥姿", "步態", "手功能", "肩頸", "腰背", "耐力", "ADL", "神經"];
window.exerciseDatabase = exerciseRows.map(([id, name, category, tagText, description, steps, defaultReps, defaultSets, caution, imageKey]) => ({
  id,
  name,
  category,
  tags: tagText.split("|"),
  description,
  steps,
  defaultReps,
  defaultSets,
  caution,
  image: imageKey.startsWith("assets/") ? imageKey : exerciseImages[imageKey]
}));
